Repository scientific-python/sync-teams-action, pull requests merged in 2024-06, with the labels that each got.

#15 Expand role description in README
  README.md
Labels: type: Documentation

#16 Enforce standard roles
  .gitignore
  sync-teams-to-gh.py
Labels: type: Maintenance

#17 Use github actions context to set org name
  action.yaml
  sync-teams-to-gh.py
Labels: type: Enhancement
